### ISSUE TITLE
npm start fails Module not found: Can't resolve 'firebase/app' in '/Users/reda/Sites/firefly/src'

### ISSUE THREAD

**Issue by Reda404** [sampl/firefly#165]
After following all the instructions of the documentation when launching the application with npm run start I get the following error message: "./src/index.js
Module not found: Can not resolve 'firebase / app' in '/ Users / reda / Sites / firefly / src' "

**Comment by jnelson180** [comment]
If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`. 

Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).

Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.

**Comment by sujae815** [comment]
Thanks.

**Comment by bilalmalik4321** [comment]
This may start because firebase is placed in the .gitignore file, it has some information that should only be accessed by the persons pushing onto the repository. In this case you need to write your own firebase.js file.

**Comment by patbi** [comment]
Thanks @jnelson180

**Comment by Carlos20001** [comment]
I am having the same isue too and it is still not helping me out now. I npm installed firebase and still get the same result ./src/firebase/config.js
Module not found: Can't resolve 'firebase/app' in 'C:\Users\Carlos R\Desktop\firegram-starter-files\firegram\src\firebase'

**Comment by yusluv1234** [comment]
please what can i do to resolve this

./src/firebase/firebase.utils.js
Module not found: Can't resolve 'firebase/app' in 'C:\Users\USER\Desktop\REACT PROJECT\easybanking\src\firebase'

**Comment by shrikantpandey13** [comment]
> 
> 
> If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> 
> Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> 
> Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.

It worked. Thank you for your contribution

**Comment by corps01** [comment]
> If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> 
> Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> 
> Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.

this worked for me thank you!

**Comment by indevi** [comment]
shd i run this command inside  my "nodemodules" directory?


> > If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> > Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> > Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.
> 
> this worked for me thank you!

**Comment by MUSTAQ1995** [comment]
No just run this command in the main directory

**Comment by shantanu16101998** [comment]
this worked for me thank you!

> If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> 
> Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> 
> Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.

**Comment by pimggwp** [comment]
> > If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> > Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> > Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.
> 
> It worked. Thank you for your contribution

This worked for me Thank youuuu.

**Comment by vibesaraf** [comment]
> If you check your `node_modules` folder and see that `firebase` isn't in it, try running `npm i firebase@6.0.2`.
> 
> Gprc is a dependency of firebase and there was a release of it awhile back that breaks on install if you're using Node 12 (or maybe some other versions, too).
> 
> Installing firebase@6.0.2 or higher will probably get your issue resolved if you're using Node 12 and your `npm i` is breaking on installing gprc.

I have firebase 8.8.0 (latest) in package.json dont know why firebase is still not there in the `node_modules`

**Comment by Bhagyeshpro** [comment]
what about if we have firebase over there I have it.

**Comment by salma-py97** [comment]
Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

**Comment by himanksuiwala** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

Thanks Man this worked, it is having issue in its latest build.

**Comment by Adelndf** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

Thank u so much i had this issue for 2 days and now it fixed .. <3

**Comment by JackXN** [comment]
Awesome!!!

**Comment by Harshguglani** [comment]
I have uninstalled the previous version, and installed the npm i firebase@^8.10.0, but i am still facing issue.

**Comment by braga-hub** [comment]
Im having issues and I have firebase in my node modules but I don't have firebase-tools even that I "npm install firebase-tools" I still don't have them and I still have this error "./src/firebase.js
Module not found: Can't resolve 'firebase' in 'C:\Users\ermis braka\first-clone\disney-clone\src' "

**Comment by Harshguglani** [comment]
> Im having issues and I have firebase in my node modules but I don't have firebase-tools even that I "npm install firebase-tools" I still don't have them and I still have this error "./src/firebase.js
> Module not found: Can't resolve 'firebase' in 'C:\Users\ermis braka\first-clone\disney-clone\src' "

perform these step
Remove your node_modules directory and your package-lock.json file.
Run npm cache clean.
Run npm install again.
Run npm i

**Comment by Royal6969** [comment]
@jnelson180 guy amazing !! how a previous version like v8 can works with no issues better than the v.9 ??

**Comment by pro-Sharad** [comment]
> > Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`
> 
> Thank u so much i had this issue for 2 days and now it fixed .. <3

Thank you it worked

**Comment by marufjs** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

Thanks. it worked.

**Comment by Aman-Paul** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

thanks, I was stuck with this problem for more than a week and, now it is solved thanks a lot.

**Comment by manvi0308** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

This worked for me as well.

**Comment by Alexchevair** [comment]
> Guys, uninstall the firebase version that you have in package.json with `npm uninstall firebase` and install this version instead `npm i firebase@^8.10.0`

Ran this directly in my \react folder. It worked! Thanks!

**Comment by haileicristina** [comment]
Pessoal, desinstale a versão do firebase que você tem no package.json npm uninstall firebasee instale esta versãonpm i firebase@^8.10.0
[salma-py97] Grate.! For me its ok

**Comment by Sova-Anton** [comment]
> 

Thank you. It's help me.

**Comment by Sova-Anton** [comment]
Pessoal, desinstale a versão do firebase que você tem no package.json npm uninstall firebasee instale esta versãonpm i firebase@^8.10.0
[salma-py97] 

Thank you!
