### ISSUE TITLE
posts _likeCount field not changing when user likes/dislikes a post

### ISSUE THREAD

**Issue by tconroy** [sampl/firefly#169]
hello. Just started playing around with this. Havent made any changes, just followed along with the docs.

When a post is liked, the `postLike` object is created, but the `_likeCount` field on the `posts` document does not change.

**Comment by sampl** [comment]
Hi, thanks for posting. Are your backend functions running? This is where
the like count happens. IIRC there are some instructions in the readme for
setting up the backend.

**Comment by tconroy** [comment]
Thanks for the reply, @sampl! 

I had forgotten to deploy the backend functions ( thanks for the reminder! ) however even once I did that I'm still not seeing the change.

Hopping into the functions section of firebase I noticed there is an error happening in `updatePostLikeCount`, `Error: process.env.GCLOUD_PROJECT is not set`. 

is this something we're supposed to set in `functions/.env.dev`? I'm not seeing it in the docs anywhere.

Thanks!

**Comment by tconroy** [comment]
Oh, nevermind! I figured it out.

I had set 
```
  "engines": {
    "node": "10"
  },
```

in `functions/package.json`. However I read online this should be `"node": "8"`. After changing that and redeploying the functions, Im seeing like count update!

Thanks for the help 👍

**Comment by sampl** [comment]
Glad it’s fixed!

Not sure why it’s not working in node 10 though, unless it’s just not
supported by fire base yet?

**Comment by tconroy** [comment]
I'm not entirely sure, but that sounds likely! It looks like the NodeJS 10 runtime is listed as pre-release in the cloud functions doc: https://cloud.google.com/functions/docs/concepts/nodejs-10-runtime
