### ISSUE TITLE
Update Stripe links to point to Stripe Checkout legacy

### ISSUE THREAD

**Issue by MarkEdmondson1234** [sampl/firefly#177]
This confused me a lot until I saw that the StripeCheckout is the legacy version

https://stripe.com/docs/legacy-checkout#integration-custom

The links in the code point to the newer version https://stripe.com/docs/checkout#integration-custom

**Comment by sampl** [comment]
Good call--done!

https://github.com/sampl/firefly/commit/9d4ea46bac8c471d92dd5a0239b6ce36c4884d41
